### ISSUE TITLE
Design Database Schema

### ISSUE THREAD

**Issue by hayatzsala** [hayatzsala/Conduit#1]
Design basic database schema
 Requirements:
1. Design the tables and the coulmns
2. Design the Relationships between the tables

**Comment by noor848** [comment]
Uml Diagram  : https://drive.google.com/file/d/1vh0hJ9E_sLWLfwXxsJpMaJc7PR1MZphU/view?usp=sharing

**Comment by hayatzsala** [comment]
@noor848 Could you please add the final design here ?

**Comment by noor848** [comment]
its in the same link above and here is the image too 

![Image](https://user-images.githubusercontent.com/54281955/196966638-157f06ce-9b77-4170-ab39-9c72eb21ef41.png)

**Comment by hayatzsala** [comment]
yeah got it, thanks
