### ISSUE TITLE
Design API Endpoints

### ISSUE THREAD

**Issue by hayatzsala** [hayatzsala/Conduit#2]
Document all endpoints you will need for:
1. Authentication User
2. User API
3. Articles API
4. Comments API

Requirements:
1. the API documentation should have endpoints routes for each API
2. Please write the Documentation and attached here to this Issue

**Comment by noor848** [comment]
initial design for Endpoint in postman :https://www.getpostman.com/collections/ccaccc55f7e55c15b67c

**Comment by hayatzsala** [comment]
![Image](https://user-images.githubusercontent.com/35167530/196038025-e49b93f9-f28f-455a-956b-4bc2a8e840dd.png)
