### ISSUE TITLE
Create Entity Models and Database Tables

### ISSUE THREAD

**Issue by noor848** [hayatzsala/Conduit#7]
- [x] Create Entity Model Classes
- [x] Create Database Tables

**Comment by hayatzsala** [comment]
@noor848 Can I have initial backup of the database please?

**Comment by noor848** [comment]
its include in branch Task #7 under this comment 
![image](https://user-images.githubusercontent.com/54281955/197073862-f5e32170-46b8-4fbe-a8ca-095a5d1e385d.png)

**Comment by noor848** [comment]
type of  file can't be uploaded here

**Comment by hayatzsala** [comment]
@noor848 okay sorry my bad, thanks
